version: "3.9"

services:

  backend:
    container_name: sb_backend
    depends_on:
      - postgres
    build:
      dockerfile: docker-devel/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}:/app

  frontend:
    depends_on:
      - postgres
    build:
      dockerfile: docker-devel/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}:/app
      - ./node_modules:/app/node_modules
      - ./bundles:/app/bundles
      - ./bundles-src:/app/bundles-src

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /opt/pgdata:/var/lib/postgresql/data
