FROM python:3.10-slim

WORKDIR /app


COPY . .

RUN pip install --prefer-binary -r requirements.txt
RUN python manage.py importmenu star-burger-products
EXPOSE 8000

ENTRYPOINT ["python", "manage.py", "runserver","0.0.0.0:8000"]