version: "3.9"

services:

  backend:
    depends_on:
      - postgres
    build:
      context: ../.
      dockerfile: docker-devel/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}:/app
    env_file:
      - ../.env
      # - ./node_modules:/app/node_modules

  frontend:
    depends_on:
      - postgres
    build:
      context: ../.
      dockerfile: docker-devel/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}:/app
      - ./node_modules:/app/node_modules
      - ./bundles:/app/bundles
      - ./bundles-src:/app/bundles-src
    env_file:
      - ../.env

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /opt/pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env

# volumes:
#   node_modules:
