# Generated by Django 3.2.15 on 2024-07-17 11:57

from django.db import migrations


def populate_price_for_orderlines(apps, schema_editor):
    OrderLine = apps.get_model("foodcartapp", "OrderLine")
    lines = OrderLine.objects.select_related("product")

    for line in lines.iterator():
        if line.price == 0:
            line.price = line.product.price
        line.save()


def undo_populate(apps, schema_editor):
    apps.get_model('foodcartapp', 'OrderLine').objects.update(
        price=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20240716_2023'),
    ]

    operations = [
        migrations.RunPython(populate_price_for_orderlines, undo_populate)
    ]
