# Generated by Django 3.2.15 on 2024-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'новый'), (1, 'готовится'), (2, 'доставляется'), (3, 'исполнен')], db_index=True, default=0, verbose_name='Статус'),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together={('order', 'product')},
        ),
    ]
