# Generated by Django 3.2.15 on 2024-07-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_assigned_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('status', '-created'), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
